name: wf1
on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
    
    
            - name: Install dependencies
              run: |
                    echo "Installing dependencies..."
                    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
                    

            - name: Run tests
              run: |
                echo "Running tests..."
                # Add your test commands here
                echo "Tests completed successfully!"


            

        
